name: Check Working Channels

on:
  schedule:
    - cron: '*/5 * * * *' # تشغيل كل 5 دقائق
  workflow_dispatch: # تشغيل يدوي من GitHub

jobs:
  fetch-and-validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests m3u8

      - name: Download M3U file
        run: |
          curl -o channels.m3u https://raw.githubusercontent.com/Khz2025/Iptv/refs/heads/main/Sup%D8%A8%D9%83%D9%88%D8%B1.m3u

      - name: Check working channels
        run: |
          python check_channels.py

      - name: Upload working channels
        uses: actions/upload-artifact@v4
        with:
          name: working_channels
          path: working_channels.m3u
