name: dlhd_player1_m3u8

on:
  schedule:
    - cron: '*/5 * * * *'  # كل 5 دقائق
  workflow_dispatch:      # لتشغيله يدويًا

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.14"
      - name: Install Requests
        run: pip install requests
      - name: Run Script
        run: python dlhd_player1_m3u8.py
      - name: Commit & Push Playlist
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add dlhd_player1_m3u8
          git commit -m "Update playlist $(date)"
          git push
