name: Filter Channels

on:
  schedule:
    - cron: '*/1 * * * *'  # يعمل كل 2 دقيقة
  workflow_dispatch:        # يمكن تشغيله يدويًا

jobs:
  filter:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - run: pip install requests

    # إذا وضعت filter.py داخل scripts/
    - run: python scripts/filter.py

    - run: |
        git config --global user.name "BOT"
        git config --global user.email "bot@github.com"
        git add KASSSSKASSSK.m3u
        git commit -m "Update alive channels" || echo "No changes"
        git push
