name: generate_rmc 

on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install libs
        run: pip install requests beautifulsoup4

      - name: Run script
        run: python scrape.py

      - name: Show files
        run: ls

      - name: Commit files
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add *.m3u
          git commit -m "generate_rmc m3u" || echo "no changes"
          git push
